blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings         
from django.conf.urls.static import static
from ka_kun_blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, CategoryListView, TagListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostListView.as_view(), name="index"),
    path('<int:pk>', PostDetailView.as_view(), name="detail"),
    path('create', PostCreateView.as_view(), name="create"),
    path('<int:pk>/update', PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete', PostDeleteView.as_view(), name="delete"),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('category/<str:category>', CategoryListView.as_view(), name="category"),
    path('tag/<str:tag>', TagListView.as_view(), name="tag"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ka_kun_blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):

    name = models.CharField('カテゴリ名', max_length=50)
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):

    name = models.CharField('タグ名', max_length=50)
    created_at = models.DateTimeField('作成日', auto_now_add=True)
 
    def __str__(self):
        return self.name

class Post(models.Model):

    title = models.CharField('タイトル', max_length=100)
    content = models.TextField('本文')
    thumnail = models.ImageField('サムネイル', upload_to='images/', null=True, blank=True)
    image = models.ImageField('画像', upload_to='images/', null=True, blank=True)
    created_at = models.DateTimeField('作成日',auto_now_add=True)
    updated_at = models.DateTimeField('更新日',auto_now=True)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="タグ")
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="カテゴリ")

    class Meta:
        ordering = ['-created_at']
    

    def __str__(self):
        return self.title

ka_kun_blog/forms.py
from django import forms
from .models import Post
from django.forms import TextInput, Textarea, FileInput, Select, SelectMultiple
from django.contrib.auth.forms import AuthenticationForm


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "thumnail", "image", "category", "tag"]
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'タイトル'}),
            'content': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '本文',
                'cols': 80, 'rows': 15}),
            'thumnail': FileInput(attrs={
                'class': 'form-control-file'}),
            'image': FileInput(attrs={
                'class': 'form-control-file'}),
            'category': Select(attrs={
                'class': 'form-control'}),
            'tag': SelectMultiple(attrs={
                'class': 'form-control'
            })
        }

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fields in self.fields.values():
            fields.widget.attrs['class'] = 'form-control'
            fields.widget.attrs['placeholder']= fields.label

ka_kun_blog/views.py
from django.shortcuts import render
from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Count, Q

# Create your views here.

class PostListView(ListView):
    model = Post
    context_object_name = "posts"
    paginate_by = 4
    
    def get_queryset(self):
        queryset = Post.objects.all().order_by('-created_at')
        search = self.request.GET.get('q')
        if search:
            queryset = Post.objects.filter(
                Q(title__icontains=search) | Q(content__icontains=search))
        return queryset


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("index")
    template_name = "ka_kun_blog/post_create_form.html"
    login_url = '/login/'

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "保存に失敗しました")
        return super().form_invalid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "ka_kun_blog/post_update_form.html"
    login_url = '/login/'

    def get_success_url(self):
        post_pk = self.kwargs['pk']
        url = reverse_lazy("detail", kwargs={"pk": post_pk})
        return url

    def form_valid(self, form):
        messages.success(self.request, "更新されました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("index")
    login_url = '/login/'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました")
        return super().delete(request, *args, **kwargs)


class CategoryListView(ListView):
    model = Post
    context_object_name = "posts"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.kwargs['category']
        return context

    def get_queryset(self):
        category = Category.objects.get(name=self.kwargs['category'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        return queryset


class TagListView(ListView):
    model = Post
    context_object_name = "posts"
    paginate_by = 4
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs['tag']
        return context
        
    def get_queryset(self):
        tag = Tag.objects.get(name=self.kwargs['tag'])
        queryset = Post.objects.order_by('-created_at').filter(tag=tag)
        return queryset

ka_kun_blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"/>
        <link rel="stylesheet" type="text/css" href="{% static 'ka_kun_blog/css/style.css' %}"/>
        
        <title>ka_kun_blog</title>
    </head>
    
    <body>
        {% include "navi.html" %} 
            <div class="container">
                {% if messages %}
                    <ul class="messages_ul" style="margin-top: 1rem;">
                        {% for message in messages %}
                            <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                
                <div class="row">
                    <main class="col-12 col-md-8">
                        {% block content %} {% endblock %}
                    </main>
                    {% include "sidebar.html" %}
                </div>
            </div>
            
            <footer style="background-color: black; padding:30px 0px;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <ul class="menu">
                                <span class="contact-form">
                                    Menu
                                </span>
                                <li class="contact-list">
                                    <a class="contact-link" href="{% url 'index' %}">
                                        Home
                                    </a>
                                </li>
                            </ul>
                        </div>
                        
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <ul class="address">
                                <span class="contact-form">
                                    Contact
                                </span>
                                <li class="contact-list">
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    <a class="contact-link" href="mailto:models.innpy@gmail.com" target="_blank">
                                        Email
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <p class="copyright">
                    © Copyright 2020 katsuhiko All rights reserved.
                </p>
            </footer>
            
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

ka_kun_blog/templates/ka_kun_blog/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <p>{{ object }} を削除していいですか?</p>
            <form method="post">
                <button class="btn btn-danger">削除する</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

ka_kun_blog/templates/ka_kun_blog/post_create_form.html
{% extends "base.html" %} 
{% load static %}

{% block content %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
        <label for="File">
            サムネイル画像
        </label>
        {{ form.thumnail }}
    </div>
    <div class="form-group">
        <label for="title">
            タイトル
        </label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="content">
            本文
        </label>
        {{ form.content }}
    </div>
    <div class="form-group">
        {{ form.image }}
    </div>
    <div class="form-group">
        {{ form.category }}
    </div>
    <div class="form-group">
        {{ form.tag }}
    </div>
    <button class="btn btn-primary" type="sumit">保存</button>
</form>

{% endblock %}

ka_kun_blog/templates/ka_kun_blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-4">かっちゃんのBlog</h1>
    <div class="col-md-12">
        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>
        <hr />
        <!-- Date/Time -->
        <p>{{ post.created_at }}</p>
        <hr />
        <!-- Preview Image -->
        {% if post.image %}
            <img class="img-fluid rounded" src="{{ post.image.url }}" alt="content_image"/> 
        {% endif %}
        <hr />
        <!-- Post Content -->
        <p class="text">
            {{ post.content}}
        </p>
        <hr />
        {% if user.is_authenticated %}
            <div class="card-footer">
                <a class="btn btn-primary" href="{% url 'update' post.pk %}">修正</a>
                <a class="btn btn-danger" href="{% url 'delete' post.pk %}">削除</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

ka_kun_blog/templates/ka_kun_blog/post_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1 class="pb-4 mb-3">かっちゃんのBlog</h1>
    {% for post in posts %}
        <div class="card post-card">

            {% if post.thumnail %}
            <img class="card-img-top" src="{{ post.thumnail.url }}" alt="Card image cap">
            {% endif %}
            
            <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">
                    {{ post.content|truncatechars:100}}
                </p>
                <a href="{% url 'detail' post.pk %}" class="btn btn-primary">続きを読む &rarr;</a>
            </div>

            <div class="card-footer text-muted">
                作成日｜{{ post.created_at }}
            </div>

        </div>
    {% endfor %}
    
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">«</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            {% endif %}
            
            {% for page in paginator.page_range %}
                <li{% if page == page_obj.number %} class="page-item" {% endif %}><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">»</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-12 mt-3">
                    <a href="{% url 'create'  %}" class="btn btn-primary">新規作成</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

ka_kun_blog/templates/ka_kun_blog/post_update_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
        <label for="File">
            サムネイル画像
        </label>
            {{ form.thumnail }}
    </div>
    <div class="form-group">
        <label for="title">
            タイトル
        </label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="content">
            本文
        </label>
        {{ form.content }}
    </div>
    <div class="form-group">
        {{ form.image }}
    </div>
    <div class="form-group">
        {{ form.category }}
    </div>
    <div class="form-group">
        {{ form.tag }}
    </div>
    <button class="btn btn-primary" type="sumit">保存</button>
</form>

{% endblock %}

ka_kun_blog/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form action="{% url 'login' %}" method="POST">
    <div class="col-md-8 offset-md-2">
        <div class="card login-card">
            <div class="card-body">
                {% for field in form %}
                    {{ field }}
                    <hr>
                {% endfor %}

                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <p>{{ error }}</p>
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-success btn-lg btn-block">ログイン</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

ka_kun_blog/templates/navi.html
<nav class="navbar navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-align-justify fa-2x"></i>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                    Home
                </a>
            </li>
            
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    ログアウト
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">
                    ログイン
                </a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'index' %}">
            <input class="form-control mr-sm-2" type="text" placeholder="Search for ..." aria-label="Search" name="q"/>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                検索
            </button>
        </form>
    </div>
</nav>
      

ka_kun_blog/templates/sidebar.html
<aside class="col-md-4">
    <!-- Search Widget -->
    <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <form class="input-group" method="GET" action="{% url 'index' %}">
                <input type="text" class="form-control" placeholder="Search for ..." name="q"/>
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">
                    検索
                </button>
            </form>
        </div>
    </div>
  
    <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for category in category_list %}
                        
                            {% if not forloop.counter|divisibleby:"2" %}
                                <li>
                                    <a class="category-link "href="{% url 'category' category %}">{{ category }}({{ category.num_posts }})</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for category in category_list %}
                            {% if forloop.counter|divisibleby:"2" %}         
                                <li>
                                    <a class="category-link" href="{% url 'category' category %}">
                                        {{ category }}({{ category.num_posts }})
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Tags Widget -->
    <div class="card my-4">
        <h5 class="card-header">Tags</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for tag in tag_list %}
                            {% if not forloop.counter|divisibleby:"2" %}
                                <li>
                                    <a class="tag-link" href="{% url 'tag' tag %}">
                                        {{ tag }}({{ tag.num_posts }})
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for tag in tag_list %}
                            {% if forloop.counter|divisibleby:"2" %}         
                                <li>
                                    <a class="tag-link" href="{% url 'tag' tag %}">
                                        {{ tag }}({{ tag.num_posts }})
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>
  